"""Pure-Python straight-bevel-gear geometry - no OCCT dependency, mirroring
`gear_math.py`'s own OCCT-free/OCCT-dependent module split
(`docs/gear-design/00-conventions.md`). This is a **spike/prototype**
module (`docs/gear-design/10-bevel-gear.md`'s own "budget real spike time"
instruction) - it resolves pitch-cone geometry and samples the spherical
involute tooth flank curve, but does not implement the full
`BevelGearFeature` six-part checklist (no dataclass Feature, no router, no
OCCT construction - see `app.document.bevel` for that, once/if this spike
is promoted to a real workstream).

**Why this is a genuinely different curve from `gear_math.py`'s planar
involute**: a spur/helical gear tooth flank is the involute of a circle -
generated by unwrapping a taut string (a straight line) from a base
*circle* in a plane. A bevel gear tooth flank is the involute of a cone -
generated by rolling a plane, without slipping, on a base *cone* whose
apex is the sphere's centre; the trace of a fixed point on that rolling
plane, confined to the sphere of a given radius (the "generating sphere"),
is the spherical involute. The rolling plane's intersection with the
generating sphere is a great circle (the spherical analogue of the
straight "string" line - both are geodesics of their respective surface),
and the base cone's intersection with the sphere is the base *circle* the
great circle rolls on - so this really is "roll a great circle without
slipping on a small circle, both living on a sphere," the direct spherical
analogue of `gear_math.involute_point`'s planar construction.

**Reference-value testing**: unlike `gear_math.py` (checked against
textbook spur gear tables), there is no existing precedent in this
codebase for spherical involute gearing, and no single well-known "textbook
example" this spike could find gives full-precision (x, y, z) points to
check against directly (see `docs/gear-design/10-bevel-gear.md`'s spike
findings). `backend/tests/test_bevel_math.py` instead leans on two
independently-checkable things: (1) the pitch-cone half-angle formula's own
stated Σ=90° reduction (`γ1 = atan(N1/N2)`), checked against exact
closed-form trig values (e.g. `atan(0.5)`, `atan(1/√3)`) that are
independently verifiable by hand/calculator, not derived from this module;
(2) the spherical involute curve's own azimuthal sweep, cross-checked
against a *second, independently-derived* closed form for the same
quantity built from Napier's rules for right spherical triangles (a
different derivation path through the same geometry - see
`spherical_involute_point`'s docstring), not merely re-deriving the same
formula and comparing it to itself.
"""

import math
from dataclasses import dataclass

from app.document.gear_math import GearGeometryError

# ---------------------------------------------------------------------------
# Pitch cone half-angles
# ---------------------------------------------------------------------------


def pitch_cone_half_angles(
    tooth_count_1: int, tooth_count_2: int, shaft_angle_degrees: float = 90.0
) -> tuple[float, float]:
    """The two mating gears' pitch cone half-angles (radians, `(gamma_1,
    gamma_2)`) for an arbitrary shaft angle `Sigma`, per
    `docs/gear-design/10-bevel-gear.md`: `gamma_1 = atan(sin(Sigma) /
    (N2/N1 + cos(Sigma)))`, `gamma_2 = Sigma - gamma_1`. At the common
    `Sigma = 90 deg` case this reduces to the textbook `gamma_1 =
    atan(N1/N2)` (`cos(90deg) = 0`, `sin(90deg) = 1`, so the general
    formula collapses to `atan(1 / (N2/N1)) = atan(N1/N2)`) - the
    known-value case `test_bevel_math.py` checks first, before trusting
    the general form for other shaft angles."""
    if tooth_count_1 < 4 or tooth_count_2 < 4:
        raise GearGeometryError("both tooth counts must be >= 4 to form a gear")
    if not (0 < shaft_angle_degrees < 180):
        raise GearGeometryError(f"shaft_angle_degrees must be in (0, 180), got {shaft_angle_degrees!r}")
    shaft_angle = math.radians(shaft_angle_degrees)
    gamma_1 = math.atan(math.sin(shaft_angle) / (tooth_count_2 / tooth_count_1 + math.cos(shaft_angle)))
    gamma_2 = shaft_angle - gamma_1
    if not (0 < gamma_1 < shaft_angle):
        raise GearGeometryError(
            f"tooth_count_1 {tooth_count_1!r}/tooth_count_2 {tooth_count_2!r}/shaft_angle_degrees "
            f"{shaft_angle_degrees!r} don't yield a valid pitch cone split"
        )
    return gamma_1, gamma_2


def base_cone_half_angle(pitch_cone_half_angle: float, pressure_angle: float) -> float:
    """The base cone half-angle `gamma_b` a spherical involute flank rolls
    off of, given this gear's own pitch cone half-angle `gamma` and the
    pressure angle `alpha` - the spherical analogue of
    `gear_math.spur_gear_geometry`'s `base_radius = pitch_radius *
    cos(pressure_angle)`.

    Derivation (Napier's rules for a right spherical triangle): let `N` be
    the cone apex/axis pole, `p0` the pitch point (on the pitch circle,
    colatitude `gamma`), and `T` the point where the spherical involute's
    generating great circle (the "line of action" great circle through
    `p0`, tangent to the base circle) touches the base circle. `T` is the
    foot of the perpendicular arc from `N` to that great circle, so arc
    `N-T = gamma_b` by definition of the base cone; the triangle `N, T,
    p0` has a right angle at `T`. The tangent to the pitch circle at `p0`
    is perpendicular to the meridian arc `N-p0`, and the line of action
    meets it at the pressure angle `alpha`, so the triangle's angle at
    `p0` (between meridian `N-p0` and side `p0-T`) is `90deg - alpha`.
    Napier's rule `sin(leg) = sin(hypotenuse) * sin(opposite angle)` with
    hypotenuse `N-p0 = gamma` and the leg `N-T = gamma_b` opposite that
    `90deg - alpha` angle gives `sin(gamma_b) = sin(gamma) * sin(90deg -
    alpha) = sin(gamma) * cos(alpha)` - the planar `cos(pressure_angle)`
    factor, carried through a sine instead of applied directly, because
    `gamma`/`gamma_b` are *angles* on the sphere where the planar
    construction has *radii*.

    Degenerate-but-independently-checkable cases (used directly as
    reference values in `test_bevel_math.py`, not just "it runs"):
    `alpha = 0` collapses this to `gamma_b = gamma` (`cos(0) = 1`, base
    cone coincides with the pitch cone, matching the planar
    `base_radius = pitch_radius` at zero pressure angle); `gamma = 90deg`
    (a crown gear) gives `gamma_b = 90deg - alpha` exactly (`sin(gamma_b) =
    cos(alpha) = sin(90deg - alpha)`)."""
    if not (0 < pitch_cone_half_angle < math.pi / 2):
        raise GearGeometryError(f"pitch_cone_half_angle must be in (0, pi/2), got {pitch_cone_half_angle!r}")
    if not (0 <= pressure_angle < math.pi / 2):
        raise GearGeometryError(f"pressure_angle must be in [0, pi/2), got {pressure_angle!r}")
    return math.asin(math.sin(pitch_cone_half_angle) * math.cos(pressure_angle))


# ---------------------------------------------------------------------------
# Spherical involute primitives
# ---------------------------------------------------------------------------


def spherical_involute_point(
    base_cone_half_angle: float, roll_angle: float, sphere_radius: float = 1.0
) -> tuple[float, float, float]:
    """One point on the spherical involute generated by rolling a great
    circle, without slipping, on the base circle of angular radius
    `base_cone_half_angle` (`gamma_b`) - the spherical analogue of
    `gear_math.involute_point`'s planar `x = r_b(cos t + t sin t)`, `y =
    r_b(sin t - t cos t)`.

    `roll_angle` (`theta`) parametrizes the *base circle's own* azimuth of
    the current point of tangency `B(theta) = (sin(gamma_b) cos(theta),
    sin(gamma_b) sin(theta), cos(gamma_b))` (a unit vector; a great circle
    of constant colatitude `gamma_b` around the +Z axis) - not the
    involute point's own azimuth, which lags behind it as the curve
    unrolls (see `spherical_involute_azimuth_at_colatitude`). The tangent
    direction to the base circle at `B(theta)` is the purely azimuthal
    unit vector `Tang(theta) = (sin(theta), -cos(theta), 0)` - the
    *decreasing*-theta direction, matching `gear_math.involute_point`'s
    own handedness (an earlier draft of this function used the opposite,
    increasing-theta sign; caught by cross-checking the flat-cone/small-
    angle instantiation of this same construction against
    `gear_math.involute_point`'s already-trusted formula bit-for-bit, and
    independently against a from-scratch rigid-body rolling simulation -
    see `10-bevel-gear.md`'s spike findings for the full story, since the
    wrong sign passed several weaker self-consistency checks and only
    this cross-check caught it). The unique great circle through
    `B(theta)` with that initial tangent is `G(s) = B(theta) cos(s) +
    Tang(theta) sin(s)`.

    Rolling without slipping ties the two arc lengths together exactly as
    the planar construction ties string length to base-circle arc: by the
    time the tangency point has swept to azimuth `theta`, it has travelled
    arc length `sin(gamma_b) * theta` along the base circle (arc length on
    a unit-sphere circle of colatitude `gamma_b` is radius `sin(gamma_b)`
    times swept angle) - the marked point, having started *at* the
    tangency point when `theta = 0` (the involute's own start, on the base
    circle itself - `roll_angle = 0` gives exactly `B(0)`, mirroring
    `involute_point(base_radius, 0) == (base_radius, 0)`), now sits that
    same arc length further along the *current* tangent great circle,
    i.e. at `G(u)` with `u = sin(gamma_b) * theta`:

    `Involute(theta) = B(theta) cos(u) + Tang(theta) sin(u)`, `u =
    sin(gamma_b) * theta`.

    This lies exactly on the unit sphere for any `theta`
    (`|B cos(u) + Tang sin(u)|^2 = cos^2(u) + sin^2(u) = 1` since `B` and
    `Tang` are orthonormal by construction) - checked directly in
    `test_bevel_math.py` as a basic sanity property, then scaled by
    `sphere_radius` (the cone distance a real flank is sampled at) since
    the base cone's own half-angle `gamma_b` is scale-invariant - the same
    spherical involute shape appears on every sphere concentric with the
    apex, just scaled, which is exactly why a single `(gamma_b, theta)` ->
    point function suffices for both the outer and inner cone curves
    `docs/gear-design/10-bevel-gear.md`'s OCCT construction needs (call
    twice, once per `sphere_radius`)."""
    if not (0 < base_cone_half_angle < math.pi / 2):
        raise GearGeometryError(f"base_cone_half_angle must be in (0, pi/2), got {base_cone_half_angle!r}")
    gamma_b = base_cone_half_angle
    theta = roll_angle
    u = math.sin(gamma_b) * theta
    cos_u, sin_u = math.cos(u), math.sin(u)
    cos_t, sin_t = math.cos(theta), math.sin(theta)
    sin_gb = math.sin(gamma_b)
    x = sphere_radius * (sin_gb * cos_t * cos_u + sin_t * sin_u)
    y = sphere_radius * (sin_gb * sin_t * cos_u - cos_t * sin_u)
    z = sphere_radius * math.cos(gamma_b) * cos_u
    return (x, y, z)


def spherical_involute_colatitude(base_cone_half_angle: float, roll_angle: float) -> float:
    """The colatitude (angle from the cone axis, radians - the spherical
    analogue of `gear_math`'s planar radius `r(t) = r_b sqrt(1+t^2)`) of
    `spherical_involute_point` at `roll_angle`, without needing to build
    the full 3D point first: `cos(colatitude) = cos(gamma_b) *
    cos(sin(gamma_b) * roll_angle)`, read directly off
    `spherical_involute_point`'s own `z` component (`z = sphere_radius *
    cos(gamma_b) * cos(u)`, and `z / sphere_radius = cos(colatitude)` by
    definition of colatitude) - kept as its own function since
    `spherical_involute_roll_angle_at_colatitude` (this function's
    inverse) and the flank-sampling range below both need it."""
    if not (0 < base_cone_half_angle < math.pi / 2):
        raise GearGeometryError(f"base_cone_half_angle must be in (0, pi/2), got {base_cone_half_angle!r}")
    u = math.sin(base_cone_half_angle) * roll_angle
    return math.acos(max(-1.0, min(1.0, math.cos(base_cone_half_angle) * math.cos(u))))


def spherical_involute_roll_angle_at_colatitude(base_cone_half_angle: float, colatitude: float) -> float:
    """Inverse of `spherical_involute_colatitude` - the spherical
    analogue of `gear_math.involute_roll_angle_at_radius`. `colatitude`
    must be at or outside the base cone (`colatitude >= base_cone_half_
    angle`) - like the planar involute, the spherical involute is only
    defined outside its own base circle (the generating great circle
    hasn't started rolling away from it yet at smaller colatitude)."""
    if colatitude < base_cone_half_angle:
        raise GearGeometryError(
            f"colatitude {colatitude!r} is inside the base cone (half-angle {base_cone_half_angle!r}) - "
            "not reachable by the spherical involute"
        )
    cos_gamma_b = math.cos(base_cone_half_angle)
    ratio = math.cos(colatitude) / cos_gamma_b
    u = math.acos(max(-1.0, min(1.0, ratio)))
    return u / math.sin(base_cone_half_angle)


def spherical_involute_azimuth_at_colatitude(base_cone_half_angle: float, colatitude: float) -> float:
    """The involute point's own azimuth (radians, around the cone axis)
    at a given `colatitude`, relative to the curve's `roll_angle = 0`
    start direction - the spherical analogue of
    `gear_math.involute_function` (`inv(alpha) = tan(alpha) - alpha`, the
    planar involute's own angular sweep from base-circle start to a given
    pressure angle), used the same way: placing a flank relative to its
    tooth's centerline (`gear_math._flank_start_offset_angle`'s spherical
    counterpart, see `_spherical_flank_start_offset_angle` below).

    Computed by evaluating `spherical_involute_point` at the `roll_angle`
    that reaches `colatitude` (via `spherical_involute_roll_angle_at_
    colatitude`) and reading off `atan2(y, x)` - not via a closed-form
    "spherical involute function" formula, because the point-evaluation
    route is simpler and no less rigorous, *and* because it leaves a
    genuinely independent closed form available for `test_bevel_math.py`
    to check this against: Napier's rule on the right spherical triangle
    `(pole N, tangency point B(theta), involute point P)` (right angle at
    `B`, legs `u = sin(gamma_b)*theta` opposite `N` and `gamma_b` opposite
    `P`, hypotenuse `colatitude` opposite the right angle) gives `sin(a) =
    sin(c) sin(A)` -> `sin(delta_phi) = sin(u) / sin(colatitude)` for the
    angle `delta_phi` at `N` between meridians to `B` and to `P`; the
    involute point *lags* the tangency point's own azimuth by this amount
    (`spherical_involute_point`'s `Tang(theta)` direction is the
    *decreasing*-theta tangent, matching `gear_math.involute_point`'s own
    handedness - see that function's docstring), so the involute's own
    azimuth is `theta - delta_phi`, not `theta + delta_phi`. A second,
    independently-derived formula for the same quantity
    (`test_bevel_math.py`'s `test_spherical_involute_azimuth_matches_
    independent_napier_rule_derivation`), not simply this function
    compared to itself."""
    roll_angle = spherical_involute_roll_angle_at_colatitude(base_cone_half_angle, colatitude)
    x, y, _z = spherical_involute_point(base_cone_half_angle, roll_angle)
    return math.atan2(y, x)


def sample_spherical_involute_flank(
    base_cone_half_angle: float,
    start_colatitude: float,
    end_colatitude: float,
    sphere_radius: float,
    point_count: int = 12,
) -> list[tuple[float, float, float]]:
    """Evenly-spaced-by-roll-angle sample of one spherical involute flank
    between `start_colatitude` and `end_colatitude`, on the sphere of
    radius `sphere_radius` centred at the cone apex (order preserved, like
    `gear_math.sample_involute_flank`) - the pure-Python "sample a
    spherical involute curve on a cone" prototype
    `docs/gear-design/10-bevel-gear.md` calls for. Call once with
    `sphere_radius = cone_distance` (outer/back cone) and once with
    `sphere_radius = cone_distance - face_width` (inner cone) to get the
    two space curves one flank's OCCT surface needs
    (`bevel_tooth_flank_pair` does exactly this for a full tooth)."""
    if point_count < 2:
        raise GearGeometryError(f"point_count must be >= 2, got {point_count!r}")
    t_start = spherical_involute_roll_angle_at_colatitude(base_cone_half_angle, start_colatitude)
    t_end = spherical_involute_roll_angle_at_colatitude(base_cone_half_angle, end_colatitude)
    return [
        spherical_involute_point(base_cone_half_angle, t_start + (t_end - t_start) * i / (point_count - 1), sphere_radius)
        for i in range(point_count)
    ]


# ---------------------------------------------------------------------------
# Bevel gear dimensions
# ---------------------------------------------------------------------------


@dataclass
class BevelGearGeometry:
    """Fully-resolved dimensions for one straight bevel gear, derived from
    module/tooth-count/shaft-angle/pressure-angle - the bevel analogue of
    `gear_math.SpurGearGeometry`. All linear dimensions in mm, measured at
    the outer (large, back-cone) end, matching how bevel gear module is
    conventionally specified; all angles in radians unless named
    `*_degrees`."""

    module: float
    tooth_count: int
    mate_tooth_count: int | None
    pressure_angle: float
    shaft_angle: float
    backlash: float
    profile_shift: float
    pitch_cone_angle: float
    pitch_radius: float
    cone_distance: float
    face_width: float
    inner_cone_distance: float
    base_cone_angle: float
    addendum: float
    dedendum: float
    addendum_angle: float
    dedendum_angle: float
    face_cone_angle: float
    root_cone_angle: float
    tooth_thickness_at_pitch: float


def bevel_gear_geometry(
    *,
    module: float,
    tooth_count: int,
    mate_tooth_count: int | None = None,
    face_width: float,
    pressure_angle_degrees: float = 20.0,
    shaft_angle_degrees: float = 90.0,
    backlash: float = 0.0,
    profile_shift: float = 0.0,
    addendum_coefficient: float = 1.0,
    dedendum_coefficient: float = 1.25,
    pitch_cone_angle_degrees: float | None = None,
) -> BevelGearGeometry:
    """Resolve one straight bevel gear's cone geometry from its generative
    parameters, mirroring `gear_math.spur_gear_geometry`'s shape as
    closely as a genuinely different tooth-flank geometry allows. Per
    `docs/gear-design/10-bevel-gear.md`, `pitch_cone_angle` is a **direct
    input** for a real `BevelGearFeature` (a standalone bevel gear doesn't
    know a future meshing partner's tooth count on its own - `11-bevel-
    pair.md`'s pairing system computes it automatically) - pass
    `pitch_cone_angle_degrees` directly for that case, which skips
    `mate_tooth_count`/`shaft_angle_degrees`-based derivation entirely
    (both become unused; `mate_tooth_count` may be omitted, and
    `BevelGearGeometry.mate_tooth_count` is `None` on the result). Omitting
    `pitch_cone_angle_degrees` (the default, `None`) keeps this spike's own
    original behaviour: `mate_tooth_count` (required in that case) +
    `shaft_angle_degrees` derive the angle via `pitch_cone_half_angles`,
    since the spike this module started as needed to exercise that formula
    directly, not just take its own output as a given.

    `addendum`/`dedendum` use the same coefficients-times-module
    convention as `gear_math.spur_gear_geometry` (`addendum_coefficient`/
    `dedendum_coefficient` default to the same 1.0/1.25 full-depth values)
    applied at the outer (large) end - the standard "equal addendum"
    bevel system, not AGMA's Gleason long-and-short-addendum system (out
    of scope for this spike, per `10-bevel-gear.md`'s "straight bevel
    only" framing)."""
    if module <= 0:
        raise GearGeometryError(f"module must be positive, got {module!r}")
    if face_width <= 0:
        raise GearGeometryError(f"face_width must be positive, got {face_width!r}")
    if not (0 < pressure_angle_degrees < 90):
        raise GearGeometryError(f"pressure_angle_degrees must be in (0, 90), got {pressure_angle_degrees!r}")
    if backlash < 0:
        raise GearGeometryError(f"backlash must be >= 0, got {backlash!r}")

    pressure_angle = math.radians(pressure_angle_degrees)
    if pitch_cone_angle_degrees is not None:
        if not (0 < pitch_cone_angle_degrees < 90):
            raise GearGeometryError(
                f"pitch_cone_angle_degrees must be in (0, 90), got {pitch_cone_angle_degrees!r}"
            )
        pitch_cone_angle = math.radians(pitch_cone_angle_degrees)
    else:
        if mate_tooth_count is None:
            raise GearGeometryError("mate_tooth_count is required when pitch_cone_angle_degrees is not given")
        pitch_cone_angle, _mate_pitch_cone_angle = pitch_cone_half_angles(
            tooth_count, mate_tooth_count, shaft_angle_degrees
        )
    shaft_angle = math.radians(shaft_angle_degrees)

    pitch_radius = module * tooth_count / 2
    cone_distance = pitch_radius / math.sin(pitch_cone_angle)
    if face_width >= cone_distance:
        raise GearGeometryError(
            f"face_width ({face_width!r}) must be less than the cone distance ({cone_distance!r}) - "
            "a tooth can't run all the way to the apex"
        )
    inner_cone_distance = cone_distance - face_width

    base_cone_angle = base_cone_half_angle(pitch_cone_angle, pressure_angle)

    addendum = module * (addendum_coefficient + profile_shift)
    dedendum = module * (dedendum_coefficient - profile_shift)
    addendum_angle = math.atan(addendum / cone_distance)
    dedendum_angle = math.atan(dedendum / cone_distance)
    face_cone_angle = pitch_cone_angle + addendum_angle
    root_cone_angle = pitch_cone_angle - dedendum_angle
    if root_cone_angle <= 0:
        raise GearGeometryError(
            f"root_cone_angle {root_cone_angle!r} is non-positive - module {module!r}/tooth_count "
            f"{tooth_count!r}/profile_shift {profile_shift!r} don't form a valid bevel gear"
        )

    circular_pitch = math.pi * module
    tooth_thickness_at_pitch = (
        circular_pitch / 2 + 2 * profile_shift * module * math.tan(pressure_angle) - backlash
    )
    if tooth_thickness_at_pitch <= 0:
        raise GearGeometryError(
            f"tooth_thickness_at_pitch {tooth_thickness_at_pitch!r} is non-positive - "
            f"backlash {backlash!r} is too large for module {module!r}"
        )
    angular_tooth_thickness = tooth_thickness_at_pitch / pitch_radius
    if angular_tooth_thickness >= 2 * math.pi / tooth_count:
        raise GearGeometryError(
            "tooth_thickness_at_pitch exceeds the space available per tooth - "
            f"tooth_count {tooth_count!r} is too low for module {module!r}/profile_shift {profile_shift!r}"
        )

    return BevelGearGeometry(
        module=module,
        tooth_count=tooth_count,
        mate_tooth_count=mate_tooth_count,
        pressure_angle=pressure_angle,
        shaft_angle=shaft_angle,
        backlash=backlash,
        profile_shift=profile_shift,
        pitch_cone_angle=pitch_cone_angle,
        pitch_radius=pitch_radius,
        cone_distance=cone_distance,
        face_width=face_width,
        inner_cone_distance=inner_cone_distance,
        base_cone_angle=base_cone_angle,
        addendum=addendum,
        dedendum=dedendum,
        addendum_angle=addendum_angle,
        dedendum_angle=dedendum_angle,
        face_cone_angle=face_cone_angle,
        root_cone_angle=root_cone_angle,
        tooth_thickness_at_pitch=tooth_thickness_at_pitch,
    )


def max_recommended_face_width(cone_distance: float) -> float:
    """Standard rule-of-thumb face-width bound: `F <= cone_distance / 3`
    (a bevel tooth thins toward the apex, so too large a face width
    relative to cone distance runs the small end of the tooth toward
    degeneracy) - per `00-conventions.md`'s non-blocking-warning
    convention, callers should surface exceeding this as a warning
    banner, not reject creation outright (a wide-face bevel gear is still
    geometrically valid, just a worse design)."""
    if cone_distance <= 0:
        raise GearGeometryError(f"cone_distance must be positive, got {cone_distance!r}")
    return cone_distance / 3


# ---------------------------------------------------------------------------
# Tooth flank point sampling (for OCCT construction to consume)
# ---------------------------------------------------------------------------


def _spherical_flank_half_thickness_angle(geometry: BevelGearGeometry) -> float:
    """Azimuthal half-angle (radians, around the gear axis) of tooth
    thickness at the pitch circle - `arc-length / radius`, the same shape
    as `gear_math._flank_start_offset_angle`'s own `tooth_thickness_at_
    pitch / (2 * pitch_radius)` term, valid unchanged here because the
    pitch circle's actual Euclidean radius (`cone_distance *
    sin(pitch_cone_angle)`) is exactly `geometry.pitch_radius` by
    definition of the pitch cone (`pitch_radius = module * tooth_count /
    2` was used to *derive* `cone_distance` above via `cone_distance =
    pitch_radius / sin(pitch_cone_angle)`, so this is circular back to the
    same radius, not a coincidence)."""
    return geometry.tooth_thickness_at_pitch / (2 * geometry.pitch_radius)


def _spherical_flank_start_offset_angle(geometry: BevelGearGeometry) -> float:
    """The azimuthal angle (radians) from a tooth's own centerline to
    where that flank's spherical involute construction "starts"
    (`roll_angle = 0`, on the base circle) - the direct spherical
    counterpart of `gear_math._flank_start_offset_angle`, same two-term
    structure (half the tooth's angular thickness at the pitch circle,
    plus the involute curve's own angular sweep from its base-circle
    start to the pitch circle)."""
    return _spherical_flank_half_thickness_angle(geometry) + spherical_involute_azimuth_at_colatitude(
        geometry.base_cone_angle, geometry.pitch_cone_angle
    )


def _rotate_about_z(point: tuple[float, float, float], angle: float) -> tuple[float, float, float]:
    """Rotate `point` counter-clockwise by `angle` radians about the +Z
    axis (the gear's own axis in this module's local frame, apex at the
    origin) - the 3D-about-an-axis analogue of `gear_math._rotate`."""
    x, y, z = point
    cos_a, sin_a = math.cos(angle), math.sin(angle)
    return (x * cos_a - y * sin_a, x * sin_a + y * cos_a, z)


def bevel_tooth_flank_pair(
    geometry: BevelGearGeometry, points_per_flank: int = 12
) -> tuple[
    tuple[list[tuple[float, float, float]], list[tuple[float, float, float]]],
    tuple[list[tuple[float, float, float]], list[tuple[float, float, float]]],
]:
    """One tooth's two flanks (right, left - mirror images across the
    tooth centerline, which sits at azimuth 0 in this local frame, apex at
    the origin, gear axis = +Z), each as `(outer_points, inner_points)` -
    two genuine 3D space curves per flank, sampled at `sphere_radius =
    geometry.cone_distance` (outer/back cone) and `geometry.inner_cone_
    distance` (`cone_distance - face_width`), exactly what
    `docs/gear-design/10-bevel-gear.md`'s OCCT construction spike needs to
    hand to `BRepOffsetAPI_ThruSections`/a ruled-surface builder - the
    pure-Python half of that spike, kept OCCT-free per this module's own
    split so it's unit-testable in this repo's dev sandbox.

    Each flank runs from `max(root_cone_angle, base_cone_angle)` (mirrors
    `gear_math.tooth_profile_points`'s own `max(dedendum_radius,
    base_radius)` clamp - a root inside the base cone is common and fine,
    the root-to-base segment isn't a pure spherical involute there, exactly
    like the planar case) to `face_cone_angle` (addendum)."""
    start_colatitude = max(geometry.root_cone_angle, geometry.base_cone_angle)
    end_colatitude = geometry.face_cone_angle
    offset = _spherical_flank_start_offset_angle(geometry)

    def flank(sphere_radius: float, mirror: bool) -> list[tuple[float, float, float]]:
        raw = sample_spherical_involute_flank(
            geometry.base_cone_angle, start_colatitude, end_colatitude, sphere_radius, points_per_flank
        )
        angle = offset if mirror else -offset
        sign = -1.0 if mirror else 1.0
        return [_rotate_about_z((x, sign * y, z), angle) for x, y, z in raw]

    right = (flank(geometry.cone_distance, mirror=False), flank(geometry.inner_cone_distance, mirror=False))
    left = (flank(geometry.cone_distance, mirror=True), flank(geometry.inner_cone_distance, mirror=True))
    return right, left
