"""Pure-Python straight-bevel-gear geometry - no OCCT dependency, mirroring
`gear_math.py`'s own OCCT-free/OCCT-dependent module split
(`docs/gear-design/00-conventions.md`). This is a **spike/prototype**
module (`docs/gear-design/10-bevel-gear.md`'s own "budget real spike time"
instruction) - it resolves pitch-cone geometry and samples the spherical
involute tooth flank curve, but does not implement the full
`BevelGearFeature` six-part checklist (no dataclass Feature, no router, no
OCCT construction - see `app.document.bevel` for that, once/if this spike
is promoted to a real workstream).

**Why this is a genuinely different curve from `gear_math.py`'s planar
involute**: a spur/helical gear tooth flank is the involute of a circle -
generated by unwrapping a taut string (a straight line) from a base
*circle* in a plane. A bevel gear tooth flank is the involute of a cone -
generated by rolling a plane, without slipping, on a base *cone* whose
apex is the sphere's centre; the trace of a fixed point on that rolling
plane, confined to the sphere of a given radius (the "generating sphere"),
is the spherical involute. The rolling plane's intersection with the
generating sphere is a great circle (the spherical analogue of the
straight "string" line - both are geodesics of their respective surface),
and the base cone's intersection with the sphere is the base *circle* the
great circle rolls on - so this really is "roll a great circle without
slipping on a small circle, both living on a sphere," the direct spherical
analogue of `gear_math.involute_point`'s planar construction.

**Reference-value testing**: unlike `gear_math.py` (checked against
textbook spur gear tables), there is no existing precedent in this
codebase for spherical involute gearing, and no single well-known "textbook
example" this spike could find gives full-precision (x, y, z) points to
check against directly (see `docs/gear-design/10-bevel-gear.md`'s spike
findings). `backend/tests/test_bevel_math.py` instead leans on two
independently-checkable things: (1) the pitch-cone half-angle formula's own
stated Σ=90° reduction (`γ1 = atan(N1/N2)`), checked against exact
closed-form trig values (e.g. `atan(0.5)`, `atan(1/√3)`) that are
independently verifiable by hand/calculator, not derived from this module;
(2) the spherical involute curve's own azimuthal sweep, cross-checked
against a *second, independently-derived* closed form for the same
quantity built from Napier's rules for right spherical triangles (a
different derivation path through the same geometry - see
`spherical_involute_point`'s docstring), not merely re-deriving the same
formula and comparing it to itself.
"""

import math
from dataclasses import dataclass, replace

from app.document.gear_math import (
    GearGeometryError,
    involute_function,
    involute_point,
    involute_roll_angle_at_radius,
)

# ---------------------------------------------------------------------------
# Pitch cone half-angles
# ---------------------------------------------------------------------------


def pitch_cone_half_angles(
    tooth_count_1: int, tooth_count_2: int, shaft_angle_degrees: float = 90.0
) -> tuple[float, float]:
    """The two mating gears' pitch cone half-angles (radians, `(gamma_1,
    gamma_2)`) for an arbitrary shaft angle `Sigma`, per
    `docs/gear-design/10-bevel-gear.md`: `gamma_1 = atan(sin(Sigma) /
    (N2/N1 + cos(Sigma)))`, `gamma_2 = Sigma - gamma_1`. At the common
    `Sigma = 90 deg` case this reduces to the textbook `gamma_1 =
    atan(N1/N2)` (`cos(90deg) = 0`, `sin(90deg) = 1`, so the general
    formula collapses to `atan(1 / (N2/N1)) = atan(N1/N2)`) - the
    known-value case `test_bevel_math.py` checks first, before trusting
    the general form for other shaft angles."""
    if tooth_count_1 < 4 or tooth_count_2 < 4:
        raise GearGeometryError("both tooth counts must be >= 4 to form a gear")
    if not (0 < shaft_angle_degrees < 180):
        raise GearGeometryError(f"shaft_angle_degrees must be in (0, 180), got {shaft_angle_degrees!r}")
    shaft_angle = math.radians(shaft_angle_degrees)
    gamma_1 = math.atan(math.sin(shaft_angle) / (tooth_count_2 / tooth_count_1 + math.cos(shaft_angle)))
    gamma_2 = shaft_angle - gamma_1
    if not (0 < gamma_1 < shaft_angle):
        raise GearGeometryError(
            f"tooth_count_1 {tooth_count_1!r}/tooth_count_2 {tooth_count_2!r}/shaft_angle_degrees "
            f"{shaft_angle_degrees!r} don't yield a valid pitch cone split"
        )
    return gamma_1, gamma_2


def base_cone_half_angle(pitch_cone_half_angle: float, pressure_angle: float) -> float:
    """The base cone half-angle `gamma_b` a spherical involute flank rolls
    off of, given this gear's own pitch cone half-angle `gamma` and the
    pressure angle `alpha` - the spherical analogue of
    `gear_math.spur_gear_geometry`'s `base_radius = pitch_radius *
    cos(pressure_angle)`.

    Derivation (Napier's rules for a right spherical triangle): let `N` be
    the cone apex/axis pole, `p0` the pitch point (on the pitch circle,
    colatitude `gamma`), and `T` the point where the spherical involute's
    generating great circle (the "line of action" great circle through
    `p0`, tangent to the base circle) touches the base circle. `T` is the
    foot of the perpendicular arc from `N` to that great circle, so arc
    `N-T = gamma_b` by definition of the base cone; the triangle `N, T,
    p0` has a right angle at `T`. The tangent to the pitch circle at `p0`
    is perpendicular to the meridian arc `N-p0`, and the line of action
    meets it at the pressure angle `alpha`, so the triangle's angle at
    `p0` (between meridian `N-p0` and side `p0-T`) is `90deg - alpha`.
    Napier's rule `sin(leg) = sin(hypotenuse) * sin(opposite angle)` with
    hypotenuse `N-p0 = gamma` and the leg `N-T = gamma_b` opposite that
    `90deg - alpha` angle gives `sin(gamma_b) = sin(gamma) * sin(90deg -
    alpha) = sin(gamma) * cos(alpha)` - the planar `cos(pressure_angle)`
    factor, carried through a sine instead of applied directly, because
    `gamma`/`gamma_b` are *angles* on the sphere where the planar
    construction has *radii*.

    Degenerate-but-independently-checkable cases (used directly as
    reference values in `test_bevel_math.py`, not just "it runs"):
    `alpha = 0` collapses this to `gamma_b = gamma` (`cos(0) = 1`, base
    cone coincides with the pitch cone, matching the planar
    `base_radius = pitch_radius` at zero pressure angle); `gamma = 90deg`
    (a crown gear) gives `gamma_b = 90deg - alpha` exactly (`sin(gamma_b) =
    cos(alpha) = sin(90deg - alpha)`)."""
    # <= pi/2 (not < ): pi/2 exactly is a real, manufactured crown gear (this
    # function's own docstring above already calls out "gamma = 90deg (a
    # crown gear) gives gamma_b = 90deg - alpha exactly" as a reference
    # case) - confirmed on-device this stays perfectly finite at the
    # boundary, no asymptote (sin(gamma_b) = cos(alpha), never zero/undefined
    # for a valid pressure_angle).
    if not (0 < pitch_cone_half_angle <= math.pi / 2):
        raise GearGeometryError(f"pitch_cone_half_angle must be in (0, pi/2], got {pitch_cone_half_angle!r}")
    if not (0 <= pressure_angle < math.pi / 2):
        raise GearGeometryError(f"pressure_angle must be in [0, pi/2), got {pressure_angle!r}")
    return math.asin(math.sin(pitch_cone_half_angle) * math.cos(pressure_angle))


# ---------------------------------------------------------------------------
# Spherical involute primitives
# ---------------------------------------------------------------------------


def spherical_involute_point(
    base_cone_half_angle: float, roll_angle: float, sphere_radius: float = 1.0
) -> tuple[float, float, float]:
    """One point on the spherical involute generated by rolling a great
    circle, without slipping, on the base circle of angular radius
    `base_cone_half_angle` (`gamma_b`) - the spherical analogue of
    `gear_math.involute_point`'s planar `x = r_b(cos t + t sin t)`, `y =
    r_b(sin t - t cos t)`.

    `roll_angle` (`theta`) parametrizes the *base circle's own* azimuth of
    the current point of tangency `B(theta) = (sin(gamma_b) cos(theta),
    sin(gamma_b) sin(theta), cos(gamma_b))` (a unit vector; a great circle
    of constant colatitude `gamma_b` around the +Z axis) - not the
    involute point's own azimuth, which lags behind it as the curve
    unrolls (see `spherical_involute_azimuth_at_colatitude`). The tangent
    direction to the base circle at `B(theta)` is the purely azimuthal
    unit vector `Tang(theta) = (sin(theta), -cos(theta), 0)` - the
    *decreasing*-theta direction, matching `gear_math.involute_point`'s
    own handedness (an earlier draft of this function used the opposite,
    increasing-theta sign; caught by cross-checking the flat-cone/small-
    angle instantiation of this same construction against
    `gear_math.involute_point`'s already-trusted formula bit-for-bit, and
    independently against a from-scratch rigid-body rolling simulation -
    see `10-bevel-gear.md`'s spike findings for the full story, since the
    wrong sign passed several weaker self-consistency checks and only
    this cross-check caught it). The unique great circle through
    `B(theta)` with that initial tangent is `G(s) = B(theta) cos(s) +
    Tang(theta) sin(s)`.

    Rolling without slipping ties the two arc lengths together exactly as
    the planar construction ties string length to base-circle arc: by the
    time the tangency point has swept to azimuth `theta`, it has travelled
    arc length `sin(gamma_b) * theta` along the base circle (arc length on
    a unit-sphere circle of colatitude `gamma_b` is radius `sin(gamma_b)`
    times swept angle) - the marked point, having started *at* the
    tangency point when `theta = 0` (the involute's own start, on the base
    circle itself - `roll_angle = 0` gives exactly `B(0)`, mirroring
    `involute_point(base_radius, 0) == (base_radius, 0)`), now sits that
    same arc length further along the *current* tangent great circle,
    i.e. at `G(u)` with `u = sin(gamma_b) * theta`:

    `Involute(theta) = B(theta) cos(u) + Tang(theta) sin(u)`, `u =
    sin(gamma_b) * theta`.

    This lies exactly on the unit sphere for any `theta`
    (`|B cos(u) + Tang sin(u)|^2 = cos^2(u) + sin^2(u) = 1` since `B` and
    `Tang` are orthonormal by construction) - checked directly in
    `test_bevel_math.py` as a basic sanity property, then scaled by
    `sphere_radius` (the cone distance a real flank is sampled at) since
    the base cone's own half-angle `gamma_b` is scale-invariant - the same
    spherical involute shape appears on every sphere concentric with the
    apex, just scaled, which is exactly why a single `(gamma_b, theta)` ->
    point function suffices for both the outer and inner cone curves
    `docs/gear-design/10-bevel-gear.md`'s OCCT construction needs (call
    twice, once per `sphere_radius`)."""
    if not (0 < base_cone_half_angle < math.pi / 2):
        raise GearGeometryError(f"base_cone_half_angle must be in (0, pi/2), got {base_cone_half_angle!r}")
    gamma_b = base_cone_half_angle
    theta = roll_angle
    u = math.sin(gamma_b) * theta
    cos_u, sin_u = math.cos(u), math.sin(u)
    cos_t, sin_t = math.cos(theta), math.sin(theta)
    sin_gb = math.sin(gamma_b)
    x = sphere_radius * (sin_gb * cos_t * cos_u + sin_t * sin_u)
    y = sphere_radius * (sin_gb * sin_t * cos_u - cos_t * sin_u)
    z = sphere_radius * math.cos(gamma_b) * cos_u
    return (x, y, z)


def spherical_involute_colatitude(base_cone_half_angle: float, roll_angle: float) -> float:
    """The colatitude (angle from the cone axis, radians - the spherical
    analogue of `gear_math`'s planar radius `r(t) = r_b sqrt(1+t^2)`) of
    `spherical_involute_point` at `roll_angle`, without needing to build
    the full 3D point first: `cos(colatitude) = cos(gamma_b) *
    cos(sin(gamma_b) * roll_angle)`, read directly off
    `spherical_involute_point`'s own `z` component (`z = sphere_radius *
    cos(gamma_b) * cos(u)`, and `z / sphere_radius = cos(colatitude)` by
    definition of colatitude) - kept as its own function since
    `spherical_involute_roll_angle_at_colatitude` (this function's
    inverse) and the flank-sampling range below both need it."""
    if not (0 < base_cone_half_angle < math.pi / 2):
        raise GearGeometryError(f"base_cone_half_angle must be in (0, pi/2), got {base_cone_half_angle!r}")
    u = math.sin(base_cone_half_angle) * roll_angle
    return math.acos(max(-1.0, min(1.0, math.cos(base_cone_half_angle) * math.cos(u))))


def spherical_involute_roll_angle_at_colatitude(base_cone_half_angle: float, colatitude: float) -> float:
    """Inverse of `spherical_involute_colatitude` - the spherical
    analogue of `gear_math.involute_roll_angle_at_radius`. `colatitude`
    must be at or outside the base cone (`colatitude >= base_cone_half_
    angle`) - like the planar involute, the spherical involute is only
    defined outside its own base circle (the generating great circle
    hasn't started rolling away from it yet at smaller colatitude)."""
    if colatitude < base_cone_half_angle:
        raise GearGeometryError(
            f"colatitude {colatitude!r} is inside the base cone (half-angle {base_cone_half_angle!r}) - "
            "not reachable by the spherical involute"
        )
    cos_gamma_b = math.cos(base_cone_half_angle)
    ratio = math.cos(colatitude) / cos_gamma_b
    u = math.acos(max(-1.0, min(1.0, ratio)))
    return u / math.sin(base_cone_half_angle)


def spherical_involute_azimuth_at_colatitude(base_cone_half_angle: float, colatitude: float) -> float:
    """The involute point's own azimuth (radians, around the cone axis)
    at a given `colatitude`, relative to the curve's `roll_angle = 0`
    start direction - the spherical analogue of
    `gear_math.involute_function` (`inv(alpha) = tan(alpha) - alpha`, the
    planar involute's own angular sweep from base-circle start to a given
    pressure angle), used the same way: placing a flank relative to its
    tooth's centerline (`gear_math._flank_start_offset_angle`'s spherical
    counterpart, see `_spherical_flank_start_offset_angle` below).

    Computed by evaluating `spherical_involute_point` at the `roll_angle`
    that reaches `colatitude` (via `spherical_involute_roll_angle_at_
    colatitude`) and reading off `atan2(y, x)` - not via a closed-form
    "spherical involute function" formula, because the point-evaluation
    route is simpler and no less rigorous, *and* because it leaves a
    genuinely independent closed form available for `test_bevel_math.py`
    to check this against: Napier's rule on the right spherical triangle
    `(pole N, tangency point B(theta), involute point P)` (right angle at
    `B`, legs `u = sin(gamma_b)*theta` opposite `N` and `gamma_b` opposite
    `P`, hypotenuse `colatitude` opposite the right angle) gives `sin(a) =
    sin(c) sin(A)` -> `sin(delta_phi) = sin(u) / sin(colatitude)` for the
    angle `delta_phi` at `N` between meridians to `B` and to `P`; the
    involute point *lags* the tangency point's own azimuth by this amount
    (`spherical_involute_point`'s `Tang(theta)` direction is the
    *decreasing*-theta tangent, matching `gear_math.involute_point`'s own
    handedness - see that function's docstring), so the involute's own
    azimuth is `theta - delta_phi`, not `theta + delta_phi`. A second,
    independently-derived formula for the same quantity
    (`test_bevel_math.py`'s `test_spherical_involute_azimuth_matches_
    independent_napier_rule_derivation`), not simply this function
    compared to itself."""
    roll_angle = spherical_involute_roll_angle_at_colatitude(base_cone_half_angle, colatitude)
    x, y, _z = spherical_involute_point(base_cone_half_angle, roll_angle)
    return math.atan2(y, x)


def sample_spherical_involute_flank(
    base_cone_half_angle: float,
    start_colatitude: float,
    end_colatitude: float,
    sphere_radius: float,
    point_count: int = 12,
) -> list[tuple[float, float, float]]:
    """Evenly-spaced-by-roll-angle sample of one spherical involute flank
    between `start_colatitude` and `end_colatitude`, on the sphere of
    radius `sphere_radius` centred at the cone apex (order preserved, like
    `gear_math.sample_involute_flank`) - the pure-Python "sample a
    spherical involute curve on a cone" prototype
    `docs/gear-design/10-bevel-gear.md` calls for. Call once with
    `sphere_radius = cone_distance` (outer/back cone) and once with
    `sphere_radius = cone_distance - face_width` (inner cone) to get the
    two space curves one flank's OCCT surface needs
    (`bevel_tooth_flank_pair` does exactly this for a full tooth)."""
    if point_count < 2:
        raise GearGeometryError(f"point_count must be >= 2, got {point_count!r}")
    t_start = spherical_involute_roll_angle_at_colatitude(base_cone_half_angle, start_colatitude)
    t_end = spherical_involute_roll_angle_at_colatitude(base_cone_half_angle, end_colatitude)
    return [
        spherical_involute_point(base_cone_half_angle, t_start + (t_end - t_start) * i / (point_count - 1), sphere_radius)
        for i in range(point_count)
    ]


# ---------------------------------------------------------------------------
# Bevel gear dimensions
# ---------------------------------------------------------------------------


@dataclass
class BevelGearGeometry:
    """Fully-resolved dimensions for one straight bevel gear, derived from
    module/tooth-count/shaft-angle/pressure-angle - the bevel analogue of
    `gear_math.SpurGearGeometry`. All linear dimensions in mm, measured at
    the outer (large, back-cone) end, matching how bevel gear module is
    conventionally specified; all angles in radians unless named
    `*_degrees`."""

    module: float
    tooth_count: int
    mate_tooth_count: int | None
    pressure_angle: float
    shaft_angle: float
    backlash: float
    profile_shift: float
    pitch_cone_angle: float
    pitch_radius: float
    cone_distance: float
    face_width: float
    inner_cone_distance: float
    base_cone_angle: float
    addendum: float
    dedendum: float
    addendum_angle: float
    dedendum_angle: float
    face_cone_angle: float
    root_cone_angle: float
    tooth_thickness_at_pitch: float


def bevel_gear_geometry(
    *,
    module: float,
    tooth_count: int,
    mate_tooth_count: int | None = None,
    face_width: float,
    pressure_angle_degrees: float = 20.0,
    shaft_angle_degrees: float = 90.0,
    backlash: float = 0.0,
    profile_shift: float = 0.0,
    addendum_coefficient: float = 1.0,
    dedendum_coefficient: float = 1.25,
    pitch_cone_angle_degrees: float | None = None,
) -> BevelGearGeometry:
    """Resolve one straight bevel gear's cone geometry from its generative
    parameters, mirroring `gear_math.spur_gear_geometry`'s shape as
    closely as a genuinely different tooth-flank geometry allows. Per
    `docs/gear-design/10-bevel-gear.md`, `pitch_cone_angle` is a **direct
    input** for a real `BevelGearFeature` (a standalone bevel gear doesn't
    know a future meshing partner's tooth count on its own - `11-bevel-
    pair.md`'s pairing system computes it automatically) - pass
    `pitch_cone_angle_degrees` directly for that case, which skips
    `mate_tooth_count`/`shaft_angle_degrees`-based derivation entirely
    (both become unused; `mate_tooth_count` may be omitted, and
    `BevelGearGeometry.mate_tooth_count` is `None` on the result). Omitting
    `pitch_cone_angle_degrees` (the default, `None`) keeps this spike's own
    original behaviour: `mate_tooth_count` (required in that case) +
    `shaft_angle_degrees` derive the angle via `pitch_cone_half_angles`,
    since the spike this module started as needed to exercise that formula
    directly, not just take its own output as a given.

    `addendum`/`dedendum` use the same coefficients-times-module
    convention as `gear_math.spur_gear_geometry` (`addendum_coefficient`/
    `dedendum_coefficient` default to the same 1.0/1.25 full-depth values)
    applied at the outer (large) end - the standard "equal addendum"
    bevel system, not AGMA's Gleason long-and-short-addendum system (out
    of scope for this spike, per `10-bevel-gear.md`'s "straight bevel
    only" framing)."""
    if module <= 0:
        raise GearGeometryError(f"module must be positive, got {module!r}")
    if face_width <= 0:
        raise GearGeometryError(f"face_width must be positive, got {face_width!r}")
    if not (0 < pressure_angle_degrees < 90):
        raise GearGeometryError(f"pressure_angle_degrees must be in (0, 90), got {pressure_angle_degrees!r}")
    if backlash < 0:
        raise GearGeometryError(f"backlash must be >= 0, got {backlash!r}")

    pressure_angle = math.radians(pressure_angle_degrees)
    if pitch_cone_angle_degrees is not None:
        # <= 90 (not < ): 90 exactly is a crown gear (flat pitch cone) - see
        # `base_cone_half_angle`'s own identical boundary and docstring.
        # `root_cone_angle <= 0`/`face_width >= cone_distance` below still
        # catch any combination that's actually degenerate.
        if not (0 < pitch_cone_angle_degrees <= 90):
            raise GearGeometryError(
                f"pitch_cone_angle_degrees must be in (0, 90], got {pitch_cone_angle_degrees!r}"
            )
        pitch_cone_angle = math.radians(pitch_cone_angle_degrees)
    else:
        if mate_tooth_count is None:
            raise GearGeometryError("mate_tooth_count is required when pitch_cone_angle_degrees is not given")
        pitch_cone_angle, _mate_pitch_cone_angle = pitch_cone_half_angles(
            tooth_count, mate_tooth_count, shaft_angle_degrees
        )
    shaft_angle = math.radians(shaft_angle_degrees)

    pitch_radius = module * tooth_count / 2
    cone_distance = pitch_radius / math.sin(pitch_cone_angle)
    if face_width >= cone_distance:
        raise GearGeometryError(
            f"face_width ({face_width!r}) must be less than the cone distance ({cone_distance!r}) - "
            "a tooth can't run all the way to the apex"
        )
    inner_cone_distance = cone_distance - face_width

    base_cone_angle = base_cone_half_angle(pitch_cone_angle, pressure_angle)

    addendum = module * (addendum_coefficient + profile_shift)
    dedendum = module * (dedendum_coefficient - profile_shift)
    addendum_angle = math.atan(addendum / cone_distance)
    dedendum_angle = math.atan(dedendum / cone_distance)
    face_cone_angle = pitch_cone_angle + addendum_angle
    root_cone_angle = pitch_cone_angle - dedendum_angle
    if root_cone_angle <= 0:
        raise GearGeometryError(
            f"root_cone_angle {root_cone_angle!r} is non-positive - module {module!r}/tooth_count "
            f"{tooth_count!r}/profile_shift {profile_shift!r} don't form a valid bevel gear"
        )

    circular_pitch = math.pi * module
    tooth_thickness_at_pitch = (
        circular_pitch / 2 + 2 * profile_shift * module * math.tan(pressure_angle) - backlash
    )
    if tooth_thickness_at_pitch <= 0:
        raise GearGeometryError(
            f"tooth_thickness_at_pitch {tooth_thickness_at_pitch!r} is non-positive - "
            f"backlash {backlash!r} is too large for module {module!r}"
        )
    angular_tooth_thickness = tooth_thickness_at_pitch / pitch_radius
    if angular_tooth_thickness >= 2 * math.pi / tooth_count:
        raise GearGeometryError(
            "tooth_thickness_at_pitch exceeds the space available per tooth - "
            f"tooth_count {tooth_count!r} is too low for module {module!r}/profile_shift {profile_shift!r}"
        )

    return BevelGearGeometry(
        module=module,
        tooth_count=tooth_count,
        mate_tooth_count=mate_tooth_count,
        pressure_angle=pressure_angle,
        shaft_angle=shaft_angle,
        backlash=backlash,
        profile_shift=profile_shift,
        pitch_cone_angle=pitch_cone_angle,
        pitch_radius=pitch_radius,
        cone_distance=cone_distance,
        face_width=face_width,
        inner_cone_distance=inner_cone_distance,
        base_cone_angle=base_cone_angle,
        addendum=addendum,
        dedendum=dedendum,
        addendum_angle=addendum_angle,
        dedendum_angle=dedendum_angle,
        face_cone_angle=face_cone_angle,
        root_cone_angle=root_cone_angle,
        tooth_thickness_at_pitch=tooth_thickness_at_pitch,
    )


def max_recommended_face_width(cone_distance: float) -> float:
    """Standard rule-of-thumb face-width bound: `F <= cone_distance / 3`
    (a bevel tooth thins toward the apex, so too large a face width
    relative to cone distance runs the small end of the tooth toward
    degeneracy) - per `00-conventions.md`'s non-blocking-warning
    convention, callers should surface exceeding this as a warning
    banner, not reject creation outright (a wide-face bevel gear is still
    geometrically valid, just a worse design)."""
    if cone_distance <= 0:
        raise GearGeometryError(f"cone_distance must be positive, got {cone_distance!r}")
    return cone_distance / 3


# Rule-of-thumb pitch-cone-angle bound beyond which this app's simple
# solid-hub construction (`app.document.bevel._assemble_gear_solid` builds
# right out from the shared apex, with no separate hub/web/bore modeling)
# tends to leave too little material around a shaft bore to be structurally
# sound - not invalid geometry (a near-flat "crown gear" close to 90 degrees
# is a real, manufactured bevel gear form - confirmed on-device that `bevel_
# gear_geometry`/`bevel_tooth_flank_pair` stay perfectly well-behaved
# arbitrarily close to 90 degrees, no asymptote), just a case where the user
# likely needs to add their own backing material (e.g. a plate behind a
# crown-like gear) rather than relying on this app's default hub. Same
# non-blocking-warning convention as `max_recommended_face_width` above.
#
# On-device feedback (CI, real pythonocc-core): this constant used to also
# have a `NEEDLE_LIKE_PITCH_CONE_ANGLE_DEGREES = 15.0` low-end counterpart,
# warning near 0 degrees the same way - dropped entirely, not just retuned.
# This project's own canonical bevel gear test fixtures
# (`tests/test_bevel_gear_feature.py`'s `_PITCH_ANGLE_6_80` = 4.29 degrees,
# `_PITCH_ANGLE_18_90` = 11.3 degrees - real 6-tooth/18-tooth pinions mating
# with an 80-/90-tooth gear, high but entirely ordinary tooth-count ratios)
# sit well inside what a 15-degree threshold flagged, and those tests assert
# `warnings == []` deliberately - a small pinion's own pitch cone getting
# acute as its mate's tooth count grows is normal geometry, not a thin-hub
# risk the way a *wide, flat* crown gear genuinely is; the asymmetry (crown
# risk real, needle risk not) makes sense in hindsight - a small gamma
# still leaves the tooth's own full radial depth as hub material near the
# apex, nothing like a flat disc's shallow axial profile.
CROWN_LIKE_PITCH_CONE_ANGLE_DEGREES = 75.0


def thin_hub_warning(pitch_cone_angle_degrees: float) -> str | None:
    """`None` if `pitch_cone_angle_degrees` is comfortably within the
    "normal" bevel gear range, otherwise a warning string explaining why
    this gear's own hub/bore material may end up too thin - callers append
    this to their own `warnings` list exactly like `max_recommended_face_
    width`'s own comparison, non-blocking."""
    if pitch_cone_angle_degrees >= CROWN_LIKE_PITCH_CONE_ANGLE_DEGREES:
        return (
            f"pitch cone angle ({pitch_cone_angle_degrees!r}°) is close to (or at) 90° - this gear is "
            "wide and shallow like a flat 'crown' gear, so a shaft bore cut into it may leave too little "
            "material around the bore to be structurally sound. You may need to add your own backing "
            "material (e.g. a plate behind the gear) for a functioning part."
        )
    return None


# ---------------------------------------------------------------------------
# Tooth flank point sampling (for OCCT construction to consume)
# ---------------------------------------------------------------------------


def _spherical_flank_half_thickness_angle(geometry: BevelGearGeometry) -> float:
    """Azimuthal half-angle (radians, around the gear axis) of tooth
    thickness at the pitch circle - `arc-length / radius`, the same shape
    as `gear_math._flank_start_offset_angle`'s own `tooth_thickness_at_
    pitch / (2 * pitch_radius)` term, valid unchanged here because the
    pitch circle's actual Euclidean radius (`cone_distance *
    sin(pitch_cone_angle)`) is exactly `geometry.pitch_radius` by
    definition of the pitch cone (`pitch_radius = module * tooth_count /
    2` was used to *derive* `cone_distance` above via `cone_distance =
    pitch_radius / sin(pitch_cone_angle)`, so this is circular back to the
    same radius, not a coincidence)."""
    return geometry.tooth_thickness_at_pitch / (2 * geometry.pitch_radius)


def _spherical_flank_start_offset_angle(geometry: BevelGearGeometry) -> float:
    """The azimuthal angle (radians) from a tooth's own centerline to
    where that flank's spherical involute construction "starts"
    (`roll_angle = 0`, on the base circle) - the direct spherical
    counterpart of `gear_math._flank_start_offset_angle`, same two-term
    structure (half the tooth's angular thickness at the pitch circle,
    plus the involute curve's own angular sweep from its base-circle
    start to the pitch circle)."""
    return _spherical_flank_half_thickness_angle(geometry) + spherical_involute_azimuth_at_colatitude(
        geometry.base_cone_angle, geometry.pitch_cone_angle
    )


TREDGOLD_MAX_PITCH_CONE_ANGLE_DEGREES = 89.5
"""Tredgold's approximation genuinely degenerates as `pitch_cone_angle` ->
90 degrees (a crown gear): the "back cone" (see `tredgold_bevel_point`'s
own docstring) has half-angle `90deg - pitch_cone_angle`, so its own apex
distance from the real apex (`cone_distance / cos(pitch_cone_angle)`) ->
infinity there - not a numerical-precision artifact, the real geometric
limit of a cone tangent to a sphere at its equator (a cylinder, apex at
infinity). `bevel_gear_geometry` itself still allows exactly 90 degrees
(a real, previously-supported crown gear case, `base_cone_half_angle`'s
own docstring calls it out explicitly) - flat-crown-gear construction via
Tredgold is real, known future work (a crown gear's own "back cone" is
simply its own flat pitch plane - no unrolling needed at all, a genuinely
different, simpler code path), not implemented here. This bound raises a
clear, actionable error well before floating-point division blows up
silently into `inf`/`nan`, rather than only failing exactly at 90."""


def equivalent_tooth_count(tooth_count: float, pitch_cone_half_angle: float) -> float:
    """Tredgold's approximation's own core substitution, `N_v = N /
    cos(gamma)` - this bevel gear's real tooth flank (generated on its own
    curved pitch cone) is approximated by the flank of an ordinary planar
    involute spur gear with this many teeth (generally non-integer - a
    continuous parameter feeding `tredgold_bevel_point`'s construction,
    never a literal manufactured tooth count), obtained by unrolling the
    gear's own "back cone" (see `tredgold_bevel_point`'s docstring) flat.
    Not otherwise used by `bevel_tooth_flank_pair` below (which derives
    the same virtual pitch radius directly, `cone_distance * tan(gamma)` -
    simpler, since it already has `cone_distance` in hand and doesn't need
    `module` separately) - kept as its own named, independently-testable
    function since it's the single most direct, textbook-checkable
    statement of what Tredgold's approximation does."""
    if not (0 < pitch_cone_half_angle < math.pi / 2):
        raise GearGeometryError(f"pitch_cone_half_angle must be in (0, pi/2), got {pitch_cone_half_angle!r}")
    return tooth_count / math.cos(pitch_cone_half_angle)


def tredgold_radius_at_colatitude(colatitude: float, pitch_cone_half_angle: float, cone_distance: float) -> float:
    """Inverse of `tredgold_bevel_point`'s own (roll-angle-driven) radial
    construction: the flat/virtual gear's own polar radius `r_v` (mm,
    Tredgold's flat/unrolled domain) whose projected 3D point lands at
    exactly `colatitude` on the sphere of radius `cone_distance` centred
    at the real cone apex - closed-form, not a numerical search.

    Derivation: `tredgold_bevel_point` maps `r_v` to `(radial, axial) =
    (r_v cos(gamma), cone_distance/cos(gamma) - r_v sin(gamma))` in the
    meridian (radial, axial) plane (`gamma` = `pitch_cone_half_angle`),
    then reads `colatitude = atan2(radial, axial)`. Setting `tan(colatitude)
    = radial / axial` and solving for `r_v`:

    `tan(colatitude) * (cone_distance/cos(gamma) - r_v sin(gamma)) = r_v
    cos(gamma)`, so `r_v = tan(colatitude) * cone_distance / (cos(gamma) *
    (cos(gamma) + tan(colatitude) * sin(gamma)))`, which simplifies
    (multiply through by `cos(colatitude)`, then use the angle-difference
    identity `cos(gamma) cos(colatitude) + sin(gamma) sin(colatitude) =
    cos(gamma - colatitude)`) to the closed form below. Checked directly:
    plugging this `r_v` back into the forward `(radial, axial)` formula
    and simplifying (`cos(gamma - colatitude) - sin(colatitude) sin(gamma)
    = cos(gamma) cos(colatitude)`, the same identity again) gives back
    `atan2(radial, axial) = colatitude` exactly, algebraically, not just
    numerically - so a flank sampled between two colatitudes obtained this
    way starts/ends at *exactly* those colatitudes on *exactly* the given
    sphere, the same guarantee `sample_spherical_involute_flank` already
    gives via its own direct colatitude parametrization. This is what lets
    a Tredgold-built flank curve connect cleanly to `app.document.bevel`'s
    existing root-land/tip-land faces (built independently from `geometry.
    root_cone_angle`/`face_cone_angle`) without a gap or overlap."""
    gamma = pitch_cone_half_angle
    if not (0 < colatitude < math.pi / 2):
        raise GearGeometryError(f"colatitude must be in (0, pi/2), got {colatitude!r}")
    denom = math.cos(gamma) * math.cos(gamma - colatitude)
    if denom <= 0:
        raise GearGeometryError(
            f"colatitude {colatitude!r} is not reachable by this bevel gear's back cone "
            f"(pitch_cone_half_angle {gamma!r})"
        )
    return cone_distance * math.sin(colatitude) / denom


def tredgold_colatitude_at_radius(r_v: float, pitch_cone_half_angle: float, cone_distance: float) -> float:
    """Forward counterpart of `tredgold_radius_at_colatitude` above: the
    colatitude a flat/virtual-domain radius `r_v` maps to, at the sphere of
    radius `cone_distance` - `tredgold_bevel_point`'s own `(radial, axial)`
    construction, minus the azimuth it doesn't need here. Used for finding
    *where* a specific `r_v` (e.g. the flat involute's own base-circle
    radius, `roll_angle = 0`) lands, the opposite direction from `tredgold_
    radius_at_colatitude`'s "what `r_v` reaches a given target colatitude" -
    `bevel_tooth_flank_pair` needs both: a target *colatitude* for the
    flank's own start/end (to connect cleanly to `root_cone_angle`/`face_
    cone_angle`), but only a target *radius* (the base circle) for its
    `max(root_cone_angle, base_colatitude)` clamp, mirroring `sample_
    spherical_involute_flank`'s own identical-shaped clamp against
    `geometry.base_cone_angle` - except Tredgold's own base-circle
    colatitude is generally a slightly different value from the true-
    spherical `base_cone_angle` (two different approximations of the same
    underlying "where does the involute construction start" question), so
    it needs its own computation rather than reusing that field."""
    gamma = pitch_cone_half_angle
    cos_g, sin_g = math.cos(gamma), math.sin(gamma)
    radial = r_v * cos_g
    axial = cone_distance / cos_g - r_v * sin_g
    return math.atan2(radial, axial)


def tredgold_bevel_point(
    base_radius_v: float, roll_angle: float, pitch_cone_half_angle: float, cone_distance: float
) -> tuple[float, float, float]:
    """One point on a straight bevel gear's tooth flank via Tredgold's
    approximation - the standard, industry-accepted way real straight (and
    spiral) bevel gears are actually cut, and this module's replacement for
    the true-spherical-involute construction (`spherical_involute_point`)
    above: on-device testing found two real, differently-sized mating bevel
    gears built via the true spherical involute independently on their own
    base cones do *not* reliably mesh without interference (confirmed via
    direct `BRepAlgoAPI_Common` overlap measurement on a real `BevelPair
    Feature`, comparable in size to a full tooth height) - the true-
    spherical construction has no guaranteed conjugate-action relationship
    between two *different* gears' independently-generated flanks the way
    Tredgold's shared-back-cone-projection method does by construction
    (any two gears of the same module/pressure angle, built this way, are
    conjugate - the same guarantee ordinary planar involute spur gears
    already rely on, now inherited via the flat/virtual-gear step below).

    Generates the ordinary *planar* involute-of-a-circle
    (`gear_math.involute_point`) on this gear's own "back cone" unrolled
    flat - the cone tangent to the real pitch sphere at the pitch circle,
    apex on the gear's own axis, half-angle `pi/2 - gamma` (`gamma` =
    `pitch_cone_half_angle`) - a standard textbook fact: the back-cone
    generatrix is perpendicular to the pitch cone's own slant line at the
    pitch point (the defining construction of a "back cone" at all). Then
    wraps that flat curve back onto the real 3D back cone.

    Derivation: unrolling a cone of half-angle `delta` preserves distance-
    from-apex exactly (a flat involute point's own polar radius `r_v`) but
    scales azimuth by `sin(delta)` (arc length at radius `r_v` on the real
    cone is `r_v * sin(delta) * real_azimuth`; unrolled flat, the same arc
    length is `r_v * flat_azimuth` - equal arc lengths give `flat_azimuth =
    real_azimuth * sin(delta)`). With `delta = pi/2 - gamma`, `sin(delta) =
    cos(gamma)`, so `real_azimuth = flat_azimuth / cos(gamma)`.

    The back cone's own apex sits on the gear's real axis, on the far side
    of the pitch point from the real apex, at distance `cone_distance /
    cos(gamma)` from the real apex (the real apex/pitch-point/back-cone-
    apex triangle has a right angle at the pitch point - the back-cone
    generatrix is perpendicular to the pitch cone's own slant there by
    definition - hypotenuse `cone_distance / cos(gamma)`, `cone_distance`
    the adjacent leg). A flat point at radius `r_v` therefore sits, in the
    real gear's own local (radial, axial) meridian-plane coordinates, at
    `radial = r_v * cos(gamma)`, `axial = cone_distance / cos(gamma) - r_v
    * sin(gamma)` (moving from the back-cone apex toward the real apex, at
    half-angle `delta` from the back cone's own axis).

    This construction lands *exactly* on the real pitch point when `r_v` =
    this gear's own virtual pitch radius, `cone_distance * tan(gamma)`
    (checked directly: `radial = cone_distance*tan(gamma)*cos(gamma) =
    cone_distance*sin(gamma)`, the real pitch radius by definition;
    `axial = cone_distance/cos(gamma) - cone_distance*tan(gamma)*sin(gamma)
    = cone_distance*(1-sin^2(gamma))/cos(gamma) = cone_distance*cos(gamma)`,
    the real pitch point's own axial coordinate) - everywhere else it's
    Tredgold's own well-known *approximation* (the back cone only touches
    the true pitch sphere exactly at the pitch circle itself, diverging
    slightly toward root/tip - the same approximation every real straight-
    or spiral-bevel gear cut this way accepts).

    The raw `(radial, axial)` point does not sit exactly on the sphere of
    radius `cone_distance` away from the pitch circle - this function
    re-projects it there anyway (reading off `colatitude = atan2(radial,
    axial)`, keeping `real_azimuth` as computed, then rebuilding the point
    at exactly `cone_distance` from the apex) so callers keep the same
    always-on-the-given-sphere guarantee `spherical_involute_point` already
    provides - the small extra correction this adds is itself part of
    Tredgold's own accepted approximation (root/tip points deviate from
    the true sphere only slightly to begin with); it's what lets `app.
    document.bevel`'s existing fixed-sphere-radius root-land/tip-land/end-
    cap machinery keep working unchanged."""
    gamma = pitch_cone_half_angle
    x_flat, y_flat = involute_point(base_radius_v, roll_angle)
    r_v = math.hypot(x_flat, y_flat)
    flat_azimuth = math.atan2(y_flat, x_flat)
    real_azimuth = flat_azimuth / math.cos(gamma)
    colatitude = tredgold_colatitude_at_radius(r_v, gamma, cone_distance)
    sin_colat = math.sin(colatitude)
    return (
        cone_distance * sin_colat * math.cos(real_azimuth),
        cone_distance * sin_colat * math.sin(real_azimuth),
        cone_distance * math.cos(colatitude),
    )


def sample_tredgold_flank(
    pitch_cone_half_angle: float,
    pressure_angle: float,
    start_colatitude: float,
    end_colatitude: float,
    sphere_radius: float,
    point_count: int = 12,
) -> list[tuple[float, float, float]]:
    """Evenly-spaced-by-roll-angle sample of one Tredgold-approximated
    bevel tooth flank between `start_colatitude` and `end_colatitude`,
    every point (not just the two endpoints) lying exactly on the sphere
    of radius `sphere_radius` - the direct drop-in replacement for
    `sample_spherical_involute_flank`, same call shape (`bevel_tooth_
    flank_pair` calls this once per `sphere_radius`, outer/inner).

    `base_radius_v`/`start_r_v`/`end_r_v` are all derived fresh at *this*
    `sphere_radius` (not reused from a different one and rescaled) -
    `pitch_radius_v = sphere_radius * tan(gamma)` (the same formula
    `tredgold_bevel_point`'s own docstring verifies at the pitch point,
    here evaluated directly since `gamma`/`sphere_radius` are already
    in hand) - which keeps `involute_roll_angle_at_radius`'s own `radius /
    base_radius` ratio internally consistent (both in real mm at this
    specific concentric sphere) without needing a separate unit-scale/
    rescale step; colatitude and azimuth are direction-only and so need no
    rescaling at all between outer/inner calls."""
    if point_count < 2:
        raise GearGeometryError(f"point_count must be >= 2, got {point_count}")
    gamma = pitch_cone_half_angle
    pitch_radius_v = sphere_radius * math.tan(gamma)
    base_radius_v = pitch_radius_v * math.cos(pressure_angle)
    # max(..., base_radius_v): when `start_colatitude` is exactly the base
    # colatitude (`tredgold_base_colatitude`'s own return value, the
    # `max(root_cone_angle, ...)` clamp in `bevel_tooth_flank_pair` picking
    # the base-circle branch), the two independent closed-form routes to
    # get there - `tredgold_radius_at_colatitude`'s trig here vs `tredgold_
    # colatitude_at_radius`'s own trig computing that same base colatitude
    # in the first place - can disagree by a a single ULP, occasionally
    # landing `start_r_v` a hair *below* `base_radius_v` where it should be
    # exactly equal; `involute_roll_angle_at_radius` rejects anything below
    # the base circle outright (by construction, the involute isn't defined
    # there). Clamping up is safe: real cases with `start_colatitude` above
    # the base colatitude already return `start_r_v > base_radius_v` with
    # room to spare, so this only ever engages exactly on that boundary.
    start_r_v = max(tredgold_radius_at_colatitude(start_colatitude, gamma, sphere_radius), base_radius_v)
    end_r_v = max(tredgold_radius_at_colatitude(end_colatitude, gamma, sphere_radius), base_radius_v)
    t_start = involute_roll_angle_at_radius(base_radius_v, start_r_v)
    t_end = involute_roll_angle_at_radius(base_radius_v, end_r_v)
    return [
        tredgold_bevel_point(
            base_radius_v, t_start + (t_end - t_start) * i / (point_count - 1), gamma, sphere_radius
        )
        for i in range(point_count)
    ]


def _tredgold_flank_start_offset_angle(geometry: BevelGearGeometry) -> float:
    """The azimuthal angle (radians, about the *real* axis) from a tooth's
    own centerline to where that flank's Tredgold-approximated involute
    construction "starts" (`roll_angle = 0`, on the back cone's own base
    circle) - the Tredgold counterpart of `_spherical_flank_start_offset_
    angle` above, same two-term structure but the second term now derived
    in the flat/virtual domain and converted back to a real azimuthal
    angle (divide by `cos(gamma)` - `tredgold_bevel_point`'s own `real_
    azimuth = flat_azimuth / cos(gamma)` relation).

    The first term (`_spherical_flank_half_thickness_angle`) needs no such
    conversion despite its name: it's `tooth_thickness_at_pitch / (2 *
    geometry.pitch_radius)`, already expressed directly in terms of the
    *real* pitch radius/circle - a real azimuthal angle to begin with, not
    something derived in the flat domain (Tredgold preserves arc length
    exactly along the pitch circle by construction, so `tooth_thickness_
    at_pitch` is the same physical arc length real or virtual; dividing by
    the *virtual* pitch radius instead and then converting back via
    `/cos(gamma)` gives the identical result - `cos(gamma) * (arc /
    (2*real_pitch_radius)) / cos(gamma) = arc / (2*real_pitch_radius)` -
    confirming this term is correctly left unconverted).

    The second term, `gear_math.involute_function(pressure_angle)`, is
    exactly the flat/virtual involute's own angular sweep from its base-
    circle start to the point where its local pressure angle equals the
    (shared, real) `pressure_angle` - which is the virtual pitch circle,
    by the same definition-of-pressure-angle reasoning `gear_math.
    _flank_start_offset_angle` already relies on for an ordinary spur
    gear, just evaluated on the flat/virtual gear here instead."""
    return _spherical_flank_half_thickness_angle(geometry) + involute_function(
        geometry.pressure_angle
    ) / math.cos(geometry.pitch_cone_angle)


def tredgold_base_colatitude(geometry: BevelGearGeometry) -> float:
    """Where Tredgold's flat/virtual involute construction "starts"
    (`roll_angle = 0`, the flat gear's own base circle, `r_v = base_
    radius_v`) actually lands, as a colatitude on the outer (`cone_
    distance`) sphere - `tredgold_colatitude_at_radius` evaluated at that
    specific `r_v`. Exposed as its own function (not inlined into `bevel_
    tooth_flank_pair`) because `app.document.bevel._assemble_gear_solid`
    needs the *identical* value for its own `start_colatitude = max(root_
    cone_angle, tredgold_base_colatitude(geometry))` (root-land placement,
    end-cap-flattening tool sizing, the spherical cap face) - it used to
    reuse `geometry.base_cone_angle` (the true-spherical field) for this,
    which is a *different* number under Tredgold and left the root-land
    face's own boundary circle not passing through the flank curve's
    actual start point (a real `BRepBuilderAPI_MakeEdge` failure caught
    on-device switching this module over). Also where this module's own
    `pitch_cone_angle -> 90 degrees` (crown gear) degeneracy guard lives
    (`TREDGOLD_MAX_PITCH_CONE_ANGLE_DEGREES`) - the first point in the
    pipeline that needs `cos(gamma)` in a denominator, so the natural place
    to fail loudly rather than downstream as an opaque near-`inf` colatitude
    or a confusing OCCT edge-construction error."""
    gamma = geometry.pitch_cone_angle
    if gamma > math.radians(TREDGOLD_MAX_PITCH_CONE_ANGLE_DEGREES):
        raise GearGeometryError(
            f"pitch_cone_angle_degrees ({math.degrees(gamma)!r}) is too close to a crown gear (90 degrees) "
            f"for Tredgold's approximation - must be <= {TREDGOLD_MAX_PITCH_CONE_ANGLE_DEGREES} degrees"
        )
    base_radius_v = geometry.cone_distance * math.tan(gamma) * math.cos(geometry.pressure_angle)
    return tredgold_colatitude_at_radius(base_radius_v, gamma, geometry.cone_distance)


def _rotate_about_z(point: tuple[float, float, float], angle: float) -> tuple[float, float, float]:
    """Rotate `point` counter-clockwise by `angle` radians about the +Z
    axis (the gear's own axis in this module's local frame, apex at the
    origin) - the 3D-about-an-axis analogue of `gear_math._rotate`."""
    x, y, z = point
    cos_a, sin_a = math.cos(angle), math.sin(angle)
    return (x * cos_a - y * sin_a, x * sin_a + y * cos_a, z)


def bevel_tooth_flank_pair(
    geometry: BevelGearGeometry, points_per_flank: int = 12
) -> tuple[
    tuple[list[tuple[float, float, float]], list[tuple[float, float, float]]],
    tuple[list[tuple[float, float, float]], list[tuple[float, float, float]]],
]:
    """One tooth's two flanks (right, left - mirror images across the
    tooth centerline, which sits at azimuth 0 in this local frame, apex at
    the origin, gear axis = +Z), each as `(outer_points, inner_points)` -
    two genuine 3D space curves per flank, sampled at `sphere_radius =
    geometry.cone_distance` (outer/back cone) and `geometry.inner_cone_
    distance` (`cone_distance - face_width`), exactly what `app.document.
    bevel`'s OCCT construction hands to `BRepOffsetAPI_ThruSections`/a
    ruled-surface builder - the pure-Python half of that construction, kept
    OCCT-free per this module's own split so it's unit-testable in this
    repo's dev sandbox.

    Built via Tredgold's approximation (`tredgold_bevel_point`'s own
    docstring has the full derivation and the on-device finding that
    motivated switching to it from the true spherical involute this
    function used before) - each flank is the ordinary planar involute of
    this gear's own "back cone," unrolled flat and wrapped back onto the
    real cone, rather than a curve confined directly to the sphere.

    Each flank runs from `max(root_cone_angle, base_colatitude)` (mirrors
    `gear_math.tooth_profile_points`'s own `max(dedendum_radius,
    base_radius)` clamp - a root inside the base circle is common and fine,
    the root-to-base segment isn't a pure involute there, exactly like the
    planar case; `base_colatitude` is Tredgold's own version of that
    boundary, generally not the same value as the true-spherical `geometry.
    base_cone_angle` - see `tredgold_colatitude_at_radius`'s docstring) to
    `face_cone_angle` (addendum)."""
    gamma = geometry.pitch_cone_angle
    start_colatitude = max(geometry.root_cone_angle, tredgold_base_colatitude(geometry))
    end_colatitude = geometry.face_cone_angle
    offset = _tredgold_flank_start_offset_angle(geometry)

    def flank(sphere_radius: float, mirror: bool) -> list[tuple[float, float, float]]:
        raw = sample_tredgold_flank(
            gamma, geometry.pressure_angle, start_colatitude, end_colatitude, sphere_radius, points_per_flank
        )
        angle = offset if mirror else -offset
        sign = -1.0 if mirror else 1.0
        return [_rotate_about_z((x, sign * y, z), angle) for x, y, z in raw]

    right = (flank(geometry.cone_distance, mirror=False), flank(geometry.inner_cone_distance, mirror=False))
    left = (flank(geometry.cone_distance, mirror=True), flank(geometry.inner_cone_distance, mirror=True))
    return right, left


# ---------------------------------------------------------------------------
# Bevel pair mesh-interference prediction (pure-math proxy for a real
# BRepAlgoAPI_Common overlap check - see docstrings below for the on-device
# findings this is built on)
# ---------------------------------------------------------------------------


MESH_MARGIN_SAFETY_BUFFER_DEGREES = 0.5
"""Empirically-calibrated safety cushion for `bevel_pair_mesh_margin_
degrees`'s own zero-crossing: on-device `BRepAlgoAPI_Common` overlap
measurements on real bevel pairs (20T/40T and a symmetric 20T/20T, module
4, face_width 15, shaft_angle 90) sweeping `pressure_angle_degrees` from
14.5 to 30 found the *measured* overlap volume reaches exactly zero at a
pressure angle whose *predicted* margin (`bevel_pair_mesh_margin_degrees`)
is only slightly positive (about +0.12 degrees for the 20T/40T case),
while a margin around -0.4 degrees still left a small (~4 mm^3) measured
residual - i.e. this margin tracks the real (nonlinear, only measurable
via an actual Boolean intersection) interference closely, but its own
zero isn't pixel-perfectly aligned with the true zero. This buffer keeps
the warning from under-firing right at that boundary."""


def bevel_pair_mesh_margin_degrees(
    intruder_face_cone_angle: float, receiver_base_colatitude: float, shaft_angle_degrees: float
) -> float:
    """How much angular clearance (degrees) exists between one bevel pair
    member's own tooth *tip* reach (`intruder_face_cone_angle`, radians -
    the colatitude its addendum extends out to, on the shared `cone_
    distance` sphere both members share by construction) and the *other*
    member's own involute-flank floor (`receiver_base_colatitude`, radians
    - `tredgold_base_colatitude`'s own return value for that member).
    Positive means clear; negative means the intruder's tip reaches past
    where the receiver's own flank/root-land material still exists - real
    geometric interference.

    On-device finding this is built on: two mating bevel gears' pitch
    cones are tangent by construction (`pitch_cone_half_angles`'s own
    `gamma_1 + gamma_2 = shaft_angle`) - the textbook condition for two
    cones with axes `shaft_angle` apart to just touch along a shared line
    without overlapping. The *same* angle-sum-vs-axis-angle relationship,
    applied to one member's *face* cone (its tooth tip reach) against the
    *other* member's *base-circle* colatitude instead of its pitch cone,
    tracks real, measured overlap volume closely across a real pressure-
    angle sweep - strongly positive `shaft_angle - sum` (this function's
    own return value) at low pressure angles where measured overlap volume
    was largest, shrinking together as pressure angle rises, both reaching
    (near-)zero within a fraction of a degree of each other.

    `root_cone_angle` (the *nominal*, dedendum-derived root) does *not*
    work in `receiver_base_colatitude`'s place here - on-device testing
    found the smaller/pinion member's own root-land face actually sits at
    its `base_colatitude` whenever `base_cone_angle` exceeds `root_cone_
    angle` for it (the involute simply can't extend down to the dedendum-
    implied root there - `bevel_tooth_flank_pair`'s own `max(root_cone_
    angle, tredgold_base_colatitude(...))` clamp), so its own dedendum has
    *zero* measured effect on real interference in that (common - a small
    pinion meshing a much larger gear) regime: doubling `dedendum_
    coefficient` on a real, otherwise-identical bevel pair changed measured
    overlap volume by 0.002%, confirming `root_cone_angle` is the wrong
    quantity to check against there and `base_colatitude` is the real one."""
    return shaft_angle_degrees - (math.degrees(intruder_face_cone_angle) + math.degrees(receiver_base_colatitude))


def _worst_bevel_pair_mesh_margin_degrees(
    geometry_1: BevelGearGeometry, geometry_2: BevelGearGeometry, shaft_angle_degrees: float
) -> tuple[float, bool]:
    """The smaller (worse) of the two directional margins - member 2's tip
    against member 1's base colatitude, and vice versa - plus which
    direction it came from (`True` if member 2 is the intruder). Shared by
    `bevel_pair_mesh_interference_warning` and the pressure-angle search
    below so both agree on which direction is binding."""
    margin_2_into_1 = bevel_pair_mesh_margin_degrees(
        geometry_2.face_cone_angle, tredgold_base_colatitude(geometry_1), shaft_angle_degrees
    )
    margin_1_into_2 = bevel_pair_mesh_margin_degrees(
        geometry_1.face_cone_angle, tredgold_base_colatitude(geometry_2), shaft_angle_degrees
    )
    if margin_2_into_1 <= margin_1_into_2:
        return margin_2_into_1, True
    return margin_1_into_2, False


def _minimum_pressure_angle_for_mesh_clearance(
    geometry_1: BevelGearGeometry, geometry_2: BevelGearGeometry, shaft_angle_degrees: float
) -> float | None:
    """Smallest shared `pressure_angle_degrees` (holding module, tooth
    counts, face width, shaft angle, and addendum/dedendum coefficients
    fixed) that clears `MESH_MARGIN_SAFETY_BUFFER_DEGREES`, found by
    bisection - on-device sweeps found the margin rises monotonically with
    pressure angle across the whole practical range, so bisection is valid
    (not just "found a value that works"). `dataclasses.replace(...,
    pressure_angle=...)` is enough to re-evaluate at a trial angle without
    rebuilding the whole `BevelGearGeometry` from scratch: `face_cone_
    angle` doesn't depend on `pressure_angle` at all (`addendum_angle =
    atan(addendum / cone_distance)`, no pressure angle in it), and `cone_
    distance` doesn't either - only `tredgold_base_colatitude` actually
    reads `pressure_angle`, so this is a cheap, pure-math search (no OCCT,
    no full geometry re-derivation) despite searching a real geometric
    property. Returns `None` if even a generously high trial angle (40
    degrees - well above any practical bevel gear pressure angle) doesn't
    clear it, rather than suggesting a number so extreme it's not a real
    recommendation."""

    def worst_margin_at(pressure_angle_degrees: float) -> float:
        pa = math.radians(pressure_angle_degrees)
        margin, _ = _worst_bevel_pair_mesh_margin_degrees(
            replace(geometry_1, pressure_angle=pa), replace(geometry_2, pressure_angle=pa), shaft_angle_degrees
        )
        return margin

    lo, hi = math.degrees(geometry_1.pressure_angle), 40.0
    if worst_margin_at(hi) < MESH_MARGIN_SAFETY_BUFFER_DEGREES:
        return None
    for _ in range(40):
        mid = (lo + hi) / 2
        if worst_margin_at(mid) >= MESH_MARGIN_SAFETY_BUFFER_DEGREES:
            hi = mid
        else:
            lo = mid
    return hi


def bevel_pair_mesh_interference_warning(
    geometry_1: BevelGearGeometry, geometry_2: BevelGearGeometry, shaft_angle_degrees: float
) -> str | None:
    """`None` if both directions of `bevel_pair_mesh_margin_degrees` clear
    `MESH_MARGIN_SAFETY_BUFFER_DEGREES`, otherwise a warning naming which
    member's tooth tip is predicted to intrude into the other's material
    and two concrete, on-device-verified remedies: a higher shared
    `pressure_angle_degrees` (`_minimum_pressure_angle_for_mesh_clearance`
    searches for and reports the smallest one that would clear it, rather
    than leaving the user to guess-and-check) - the only lever actually
    offered here, since it's the only one of the remedies this module's own
    on-device testing found effective that's *also* a real, user-settable
    field on `BevelPairFeature` today. A smaller `addendum_coefficient`
    (shorter/"stub" teeth) was independently confirmed on-device to widen
    this same margin too - the standard real-world alternative to a higher
    pressure angle for exactly this kind of interference - but `bevel_gear_
    geometry`'s `addendum_coefficient` parameter has no corresponding field
    on `BevelPairFeature`/`BevelPairMemberSpec` (always its hardcoded 1.0
    default), so suggesting it here would tell a user to change something
    the app doesn't yet let them touch; exposing it is real, separate future
    work, not something to gesture at in a warning string. `module`
    deliberately isn't offered as a suggestion either - confirmed on-device
    to have *no* effect on this margin at all (every term in `bevel_pair_
    mesh_margin_degrees` is a pure angle, and module is a scale factor that
    cancels out of every one of them), unlike the intuitive guess that a
    smaller module might reduce interference the way it reduces overall
    gear size.

    Both directions are checked independently (`member_1`'s tip against
    `member_2`'s base colatitude, and vice versa) since the relationship
    isn't symmetric - which member's tip actually reaches into the other's
    material depends on the specific pitch-cone-angle split (a function of
    both tooth counts and shaft angle together), not a simple "smaller
    tooth count" rule."""
    worst_margin, member_2_is_intruder = _worst_bevel_pair_mesh_margin_degrees(
        geometry_1, geometry_2, shaft_angle_degrees
    )
    if worst_margin >= MESH_MARGIN_SAFETY_BUFFER_DEGREES:
        return None

    intruder_label = "member_2" if member_2_is_intruder else "member_1"
    receiver_label = "member_1" if member_2_is_intruder else "member_2"
    current_pressure_angle_degrees = math.degrees(geometry_1.pressure_angle)
    suggested_pressure_angle = _minimum_pressure_angle_for_mesh_clearance(geometry_1, geometry_2, shaft_angle_degrees)
    pressure_angle_suggestion = (
        f"raising pressure_angle_degrees to at least {suggested_pressure_angle:.1f}° (currently "
        f"{current_pressure_angle_degrees!r}°)"
        if suggested_pressure_angle is not None
        else f"raising pressure_angle_degrees well above its current {current_pressure_angle_degrees!r}°"
    )
    if worst_margin < 0:
        situation = (
            f"{intruder_label}'s tooth tip is predicted to intrude into {receiver_label}'s tooth material "
            f"where they mesh (about {-worst_margin:.2f}° short of clearing) - the two gears will likely not "
            "mesh cleanly at these settings."
        )
    else:
        # 0 <= worst_margin < MESH_MARGIN_SAFETY_BUFFER_DEGREES: this margin's own
        # zero-crossing isn't pixel-perfectly aligned with a real measured
        # overlap's own zero (see MESH_MARGIN_SAFETY_BUFFER_DEGREES's own
        # docstring) - technically predicted clear, but close enough to that
        # boundary that small real-world/floating-point variation could tip
        # it either way, so still worth flagging rather than staying silent.
        situation = (
            f"{intruder_label}'s tooth tip is predicted to pass very close to {receiver_label}'s tooth "
            f"material where they mesh (only {worst_margin:.2f}° of margin) - close enough to the edge of "
            "interfering that small geometry changes could tip it either way."
        )
    return f"{situation} Try {pressure_angle_suggestion} - changing module alone will not help."
